<a href="https://colab.research.google.com/github/ksmorozov7/Portfolio/blob/main/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Заливка данных

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import sqlite3

In [ ]:
sqlite3.sqlite_version

'3.45.1'

In [ ]:
! ls '/content/drive/My Drive/data'

german_credit_augmented.csv  german_credit.db

In [ ]:
con = sqlite3.connect('/content/drive/My Drive/data/german_credit.db')

Ссылка для скачивания данных на Google Drive https://drive.google.com/file/d/1Gj0qVU0Acv-HqRjTIEwvkO4TqJYijehR/view?usp=sharing

In [ ]:
!gdown --id 1Gj0qVU0Acv-HqRjTIEwvkO4TqJYijehR

/usr/local/lib/python3.13/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1Gj0qVU0Acv-HqRjTIEwvkO4TqJYijehR
To: /content/german_credit_augmented.csv
100% 69.6k/69.6k [00:00<00:00, 51.1MB/s]

In [ ]:
df = pd.read_csv('/content/german_credit_augmented.csv')

In [ ]:
df.head()

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,NaN,NaN,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,NaN,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,NaN,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,NaN,776,12,radio/TV,0,2007-07-21 13:22:14,358

In [ ]:
df['contract_dt'] = pd.to_datetime(df['contract_dt'],format='%Y-%m-%d %H:%M:%S')

In [ ]:
df.dtypes

age                          int64
sex                         object
job                          int64
housing                     object
saving_accounts             object
checking_account            object
credit_amount                int64
duration                     int64
purpose                     object
default                      int64
contract_dt         datetime64[ns]
client_id                    int64
dtype: object

In [ ]:
df.to_sql('german_credit',con,index=False,if_exists='replace')

1000

# Select

## Псевдонимы

In [ ]:
def select(sql):
  return pd.read_sql(sql,con)

In [ ]:
sql = '''SELECT t.age * 3 AS age_mult3,
       t.housing
FROM german_credit AS t
'''

In [ ]:
select(sql)

     age_mult3 housing
0           99     own
1          129     own
2          156     own
3          105     own
4           84     own
..         ...     ...
995        195    free
996         90     own
997         99     own
998         87     own
999        132     own

[1000 rows x 2 columns]

## Манипуляции со столбцами

In [ ]:
sql = '''select t.*,
t.age * 3 as age_mult3,
t.age + t.credit_amount as age_plus_amount,
t.age * 1.0 / t.credit_amount as age_div_amount,

t.age as age_2


 from german_credit t'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id,age_mult3,age_plus_amount,age_div_amount,age_2
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210,99,3107,0.010735,33
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929,129,1387,0.031994,43
2,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200,156,988,0.055556,52
3,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45,105,1428,0.025126,35
4,28,male,2,own,little,None,776,12,radio/TV,0,2007-07-21 13:22:14,358,84,804,0.036082,28
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,65,male,2,free,little,little,2600,18,radio/TV,1,2007-12-16 20:17:19,624,195,2665,0.025000,65
996,30,male,3,own,little,moderate,4455,36,business,1,2007-07-12 14:08:58,181,90,4485,0.006734,30
997,33,male,2,own,little,moderate,6403,24,radio/TV,0,2008-04-08 03:24:26,730,99,6436,0.005154,33
998,29,female,2,own,None,None,5003,21,car,1,2007-11-29 15:51:45,557,87,5032,0.005797,29
999,44,male,2,own,moderate,moderate,1804,12,car,0,2007-08-14 09:05:33,23,132,1848,0.024390,44

## Where

In [ ]:
df.head()

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,NaN,NaN,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,NaN,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,NaN,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,NaN,776,12,radio/TV,0,2007-07-21 13:22:14,358

In [ ]:
sql = '''select * from german_credit t limit 5'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,None,776,12,radio/TV,0,2007-07-21 13:22:14,358

In [ ]:
sql = '''select count(1) from german_credit t
where t.contract_dt between '2007-01-01' and '2007-12-31'
'''

In [ ]:
select(sql)

   count(1)
0       573

In [ ]:
sql = '''select * from german_credit t
where t.contract_dt between '2007-01-01' and '2007-12-31'
and t.purpose in ('car' ,'repairs')

order by t.contract_dt desc, credit_amount
'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,36,male,3,rent,None,moderate,7057,20,car,0,2007-12-29 16:10:08,99
1,30,male,2,own,little,moderate,639,12,repairs,1,2007-12-28 17:09:43,127
2,25,male,2,rent,moderate,moderate,1264,15,car,1,2007-12-28 08:38:58,979
3,48,male,2,own,little,None,2134,9,car,0,2007-12-24 16:28:30,20
4,67,female,2,own,little,moderate,3872,18,repairs,0,2007-12-24 12:25:28,779
...,...,...,...,...,...,...,...,...,...,...,...,...
192,55,male,2,own,rich,None,1413,12,car,0,2007-05-05 06:35:11,209
193,55,female,0,free,little,little,1190,18,repairs,1,2007-05-05 00:14:17,429
194,47,male,3,own,little,moderate,1209,6,car,1,2007-05-03 10:29:01,485
195,36,male,2,own,little,moderate,884,18,car,1,2007-05-02 06:22:11,184
196,31,male,2,own,little,None,2775,18,car,1,2007-05-01 23:14:02,598

## Like

In [ ]:
t = pd.DataFrame({'purpose':['машина','на машину','на покупку машины','автомобиль','на возвращение 2007'],
              'amount':[1000,400,600,700,1500]})

In [ ]:
t

               purpose  amount
0               машина    1000
1            на машину     400
2    на покупку машины     600
3           автомобиль     700
4  на возвращение 2007    1500

In [ ]:
t.to_sql('purpose',con,index=False,if_exists='replace')

5

In [ ]:
sql = '''select * from purpose t'''

In [ ]:
select(sql)

               purpose  amount
0               машина    1000
1            на машину     400
2    на покупку машины     600
3           автомобиль     700
4  на возвращение 2007    1500

In [ ]:
sql = '''select * from purpose t
where (t.purpose like '%машин%'
or t.purpose like '%авто%') and t.amount > 500
'''

In [ ]:
select(sql)

             purpose  amount
0             машина    1000
1  на покупку машины     600
2         автомобиль     700

In [ ]:
sql = '''select count(*) from german_credit t'''

In [ ]:
select(sql)

   count(*)
0      1000

In [ ]:
sql = '''select count(*) from german_credit t
where t.credit_amount > 1000'''

In [ ]:
select(sql)

   count(*)
0       884

In [ ]:
884/1000

0.884

In [ ]:
sql = '''select t.credit_amount,
case when t.credit_amount > 1000 then 1 else 0 end as greater_1000_flag,

iif(t.credit_amount > 1000,1,0) as greater_1000_flag2

 from german_credit t'''

In [ ]:
select(sql)

     credit_amount  greater_1000_flag  greater_1000_flag2
0             3074                  1                   1
1             1344                  1                   1
2              936                  0                   0
3             1393                  1                   1
4              776                  0                   0
..             ...                ...                 ...
995           2600                  1                   1
996           4455                  1                   1
997           6403                  1                   1
998           5003                  1                   1
999           1804                  1                   1

[1000 rows x 3 columns]

In [ ]:
sql = '''select
avg(case when t.credit_amount > 1000 then 1 else 0 end) as greater_1000_frac
 from german_credit t'''

In [ ]:
select(sql)

   greater_1000_frac
0              0.884

## Crate table

In [ ]:
sql = '''select * from german_credit t
where t.credit_amount > 1000'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
3,27,female,2,own,little,moderate,1295,18,furniture/equipment,0,2008-06-18 04:10:05,86
4,26,male,2,own,little,little,4370,42,radio/TV,1,2007-11-29 00:20:44,639
...,...,...,...,...,...,...,...,...,...,...,...,...
879,65,male,2,free,little,little,2600,18,radio/TV,1,2007-12-16 20:17:19,624
880,30,male,3,own,little,moderate,4455,36,business,1,2007-07-12 14:08:58,181
881,33,male,2,own,little,moderate,6403,24,radio/TV,0,2008-04-08 03:24:26,730
882,29,female,2,own,None,None,5003,21,car,1,2007-11-29 15:51:45,557
883,44,male,2,own,moderate,moderate,1804,12,car,0,2007-08-14 09:05:33,23

In [ ]:
cur = con.cursor()

In [ ]:
sql = '''
drop table if exists greater_1000_credit;
create table greater_1000_credit as
select * from german_credit t
where t.credit_amount > 1000'''

In [ ]:
cur.executescript(sql)

In [ ]:
sql = '''select * from greater_1000_credit t'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
3,27,female,2,own,little,moderate,1295,18,furniture/equipment,0,2008-06-18 04:10:05,86
4,26,male,2,own,little,little,4370,42,radio/TV,1,2007-11-29 00:20:44,639
...,...,...,...,...,...,...,...,...,...,...,...,...
879,65,male,2,free,little,little,2600,18,radio/TV,1,2007-12-16 20:17:19,624
880,30,male,3,own,little,moderate,4455,36,business,1,2007-07-12 14:08:58,181
881,33,male,2,own,little,moderate,6403,24,radio/TV,0,2008-04-08 03:24:26,730
882,29,female,2,own,None,None,5003,21,car,1,2007-11-29 15:51:45,557
883,44,male,2,own,moderate,moderate,1804,12,car,0,2007-08-14 09:05:33,23

## Union all and Union

In [ ]:
jan = pd.DataFrame({'month':['jan','jan'],'revenue':[1,2]})
feb = pd.DataFrame({'month':['feb','feb'],'revenue':[1,2]})

In [ ]:
jan.to_sql('jan',con,index=False,if_exists='replace')
feb.to_sql('feb',con,index=False,if_exists='replace')

2

In [ ]:
sql = '''select * from jan t
union all
select * from feb t'''

In [ ]:
select(sql)

  month  revenue
0   jan        1
1   jan        2
2   feb        1
3   feb        2

In [ ]:
sql = '''select t.revenue from jan t
union
select t.revenue from feb t'''

In [ ]:
select(sql)

   revenue
0        1
1        2

In [ ]:
sql = '''select t.revenue,
'jan' as month
 from jan t
union all
select t.revenue,
'mar' as month
 from feb t'''

In [ ]:
select(sql)

   revenue month
0        1   jan
1        2   jan
2        1   mar
3        2   mar

## Специальные функции

In [ ]:
sql = '''select t.sex, substr(t.sex,1,1) from german_credit t'''

In [ ]:
select(sql)

        sex substr(t.sex,1,1)
0      male                 m
1      male                 m
2      male                 m
3    female                 f
4      male                 m
..      ...               ...
995    male                 m
996    male                 m
997    male                 m
998  female                 f
999    male                 m

[1000 rows x 2 columns]

# Group by

## Сводная таблица

In [ ]:
sql = '''
select
t.sex,

count(*) as cnt,
avg(t.credit_amount) as credit_amount_avg

  from german_credit t
  group by t.sex
'''

In [ ]:
select(sql)

      sex  cnt  credit_amount_avg
0  female  310        2877.774194
1    male  690        3448.040580

In [ ]:
df.groupby('sex')['credit_amount'].agg(['count','mean'])

        count         mean
sex
female    310  2877.774194
male      690  3448.040580

In [ ]:
sql = '''select count(distinct t.housing), count(t.housing) from german_credit t'''

In [ ]:
select(sql)

   count(distinct t.housing)  count(t.housing)
0                          3              1000

In [ ]:
sql = '''
select
t.housing,

count(*) as cnt,
avg(t.credit_amount) as credit_amount_avg

  from german_credit t
  group by t.housing
'''

In [ ]:
select(sql)

  housing  cnt  credit_amount_avg
0    free  108        4906.212963
1     own  713        3060.939691
2    rent  179        3122.553073

## Пропуски

In [ ]:
sql = '''select count(t.checking_account), count(0) from german_credit t'''

In [ ]:
select(sql)

   count(t.checking_account)  count(0)
0                        606      1000

In [ ]:
sql = '''
select
t.checking_account,

count(*) as cnt,
avg(t.credit_amount) as credit_amount_avg

  from german_credit t
  group by t.checking_account
'''

In [ ]:
select(sql)

  checking_account  cnt  credit_amount_avg
0             None  394        3133.101523
1           little  274        3175.218978
2         moderate  269        3827.561338
3             rich   63        2177.650794

In [ ]:
df.groupby('checking_account',dropna=False)['credit_amount'].count()

checking_account
little      274
moderate    269
rich         63
NaN         394
Name: credit_amount, dtype: int64

In [ ]:
sql = '''select
sum(case when t.checking_account is null then 1 else 0 end) as is_null,

count(case when t.checking_account is null then 1 else null end) as is_null2

 from german_credit t'''

In [ ]:
select(sql)

   is_null  is_null2
0      394       394

In [ ]:
t = pd.DataFrame({'col1':[1,np.nan,2]})

In [ ]:
t

   col1
0   1.0
1   NaN
2   2.0

In [ ]:
t.to_sql('null_test',con,index=False, if_exists='replace')

3

In [ ]:
t

   col1
0   1.0
1   NaN
2   2.0

In [ ]:
(1+2)/3

1.0

In [ ]:
(1+0+2)/3

1.0

In [ ]:
(1+2)/2

1.5

In [ ]:
sql = '''select avg(t.col1) from null_test t'''

In [ ]:
select(sql)

   avg(t.col1)
0          1.5

In [ ]:
sql = '''select

t.checking_account,

coalesce(t.checking_account, 'no_info')

from german_credit t'''

In [ ]:
select(sql)

    checking_account coalesce(t.checking_account, 'no_info')
0               None                                 no_info
1             little                                  little
2               None                                 no_info
3               None                                 no_info
4               None                                 no_info
..               ...                                     ...
995           little                                  little
996         moderate                                moderate
997         moderate                                moderate
998             None                                 no_info
999         moderate                                moderate

[1000 rows x 2 columns]

In [ ]:
sql = '''select avg(coalesce(t.col1,0)) from null_test t'''

In [ ]:
select(sql)

   avg(coalesce(t.col1,0))
0                      1.0

In [ ]:
t = pd.DataFrame({'col1':[1,np.nan,2],
                  'col2':[np.nan,np.nan,1],
                  'col3':[1,2,3]})

In [ ]:
t

   col1  col2  col3
0   1.0   NaN     1
1   NaN   NaN     2
2   2.0   1.0     3

In [ ]:
t.to_sql('null_test',con,index=False,if_exists='replace')

3

In [ ]:
sql = '''select t.*, coalesce(t.col1,t.col2,t.col3) from null_test t'''

In [ ]:
select(sql)

   col1  col2  col3  coalesce(t.col1,t.col2,t.col3)
0   1.0   NaN     1                             1.0
1   NaN   NaN     2                             2.0
2   2.0   1.0     3                             2.0

## Дубликаты

In [ ]:
t = pd.DataFrame({'id':[1,1,2],'name':['a','a','b']})

In [ ]:
t

   id name
0   1    a
1   1    a
2   2    b

In [ ]:
t.to_sql('dupl_test',con,index=False,if_exists='replace')

3

In [ ]:
sql = '''select * from dupl_test t'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    a
2   2    b

In [ ]:
sql = '''select t.id, t.name, count(1) as cnt from dupl_test t
group by t.id, t.name'''

In [ ]:
select(sql)

   id name  cnt
0   1    a    2
1   2    b    1

In [ ]:
sql = '''select t.id, t.name, count(1) as cnt from dupl_test t
group by t.id, t.name
having count(1) > 1'''

In [ ]:
select(sql)

   id name  cnt
0   1    a    2

In [ ]:
t = pd.DataFrame({'id':[1,1,2,2,3],'name':['a','b','c','d','e']})

In [ ]:
t

   id name
0   1    a
1   1    b
2   2    c
3   2    d
4   3    e

In [ ]:
t.to_sql('dupl_test', con, index=False,if_exists='replace')

5

In [ ]:
sql = '''select * from dupl_test t'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d
4   3    e

In [ ]:
sql = '''select t.id, count(1) as cnt from dupl_test t
group by t.id
having count(1) > 1'''

In [ ]:
select(sql)

   id  cnt
0   1    2
1   2    2

In [ ]:
sql = '''select * from dupl_test t
where t.id in (1,2)'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d

In [ ]:
sql = '''select t.id as cnt from dupl_test t
group by t.id
having count(1) > 1
'''

In [ ]:
select(sql)

   cnt
0    1
1    2

In [ ]:
sql = '''select * from dupl_test t
where t.id in (select t.id as cnt from dupl_test t
group by t.id
having count(1) > 1)
'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d

## Агрегация

In [ ]:
sql = '''select date(t.contract_dt, 'start of month') as month,
count(1) as credit_cnt,
count(distinct t.client_id) as client_id_unique,
sum(t.credit_amount) as credit_amount_sum,
avg(t.credit_amount) as credit_amount_avg

  from german_credit t
  group by date(t.contract_dt, 'start of month')
  order by date(t.contract_dt, 'start of month')
  '''

In [ ]:
select(sql)

,month,credit_cnt,client_id_unique,credit_amount_sum,credit_amount_avg
0,2007-05-01,81,81,207663,2563.740741
1,2007-06-01,74,74,239594,3237.756757
2,2007-07-01,71,71,224333,3159.619718
3,2007-08-01,57,57,178569,3132.789474
4,2007-09-01,58,58,186909,3222.568966
5,2007-10-01,70,70,188534,2693.342857
6,2007-11-01,87,87,300504,3454.068966
7,2007-12-01,77,77,273973,3558.090909
8,2008-01-01,93,93,288080,3097.634409
9,2008-02-01,55,55,211128,3838.690909
10,2008-03-01,63,63,204944,3253.079365
11,2008-04-01,85,85,305409,3593.047059
12,2008-05-01,67,67,263043,3926.014925
13,2008-06-01,62,62,198575,3202.822581

In [ ]:
pd.Series(range(600)).sample(1000,replace=True)

364    364
7        7
155    155
226    226
170    170
      ...
357    357
488    488
592    592
400    400
244    244
Length: 1000, dtype: int64

In [ ]:
df['client_id_2'] = pd.Series(range(600)).sample(1000,replace=True).values

In [ ]:
df.head()

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id,client_id_2
0,33,male,2,own,NaN,NaN,3074,9,radio/TV,0,2008-06-29 18:52:00,210,245
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929,391
2,52,male,2,own,quite rich,NaN,936,9,education,0,2008-04-27 08:23:07,200,544
3,35,female,3,own,little,NaN,1393,11,car,0,2007-05-06 10:58:22,45,596
4,28,male,2,own,little,NaN,776,12,radio/TV,0,2007-07-21 13:22:14,358,373

In [ ]:
df.to_sql('german_credit_not_unieque',con,index=False,if_exists='replace')

1000

In [ ]:
sql = '''select
date(t.contract_dt,'start of month') as month,
count(1) as credit_cnt,
count(distinct t.client_id_2) as client_id_unique,
sum(t.credit_amount) as credit_amount_sum,
avg(t.credit_amount) as credit_amount_avg

 from german_credit_not_unieque t
 group by date(t.contract_dt,'start of month')
 order by date(t.contract_dt,'start of month')
 '''

In [ ]:
select(sql)

,month,credit_cnt,client_id_unique,credit_amount_sum,credit_amount_avg
0,2007-05-01,81,73,207663,2563.740741
1,2007-06-01,74,70,239594,3237.756757
2,2007-07-01,71,68,224333,3159.619718
3,2007-08-01,57,55,178569,3132.789474
4,2007-09-01,58,55,186909,3222.568966
5,2007-10-01,70,66,188534,2693.342857
6,2007-11-01,87,79,300504,3454.068966
7,2007-12-01,77,71,273973,3558.090909
8,2008-01-01,93,86,288080,3097.634409
9,2008-02-01,55,51,211128,3838.690909
10,2008-03-01,63,60,204944,3253.079365
11,2008-04-01,85,79,305409,3593.047059
12,2008-05-01,67,61,263043,3926.014925
13,2008-06-01,62,61,198575,3202.822581

## Интервалы (или бины или бакеты)

In [ ]:
sql = '''select count(distinct t.credit_amount) from german_credit t'''

In [ ]:
select(sql)

   count(distinct t.credit_amount)
0                              921

In [ ]:
sql = '''select t.credit_amount,

case when t.credit_amount < 1000 then '1. < 1000'
when t.credit_amount < 2000 then '2. < 1000-2000'
when t.credit_amount < 3000 then '3. < 2000-3000'
when t.credit_amount >= 3000 then '4. >= 3000'

else 'other' end as credit_amount_bin

  from german_credit t
'''

In [ ]:
select(sql)

     credit_amount credit_amount_bin
0             3074        4. >= 3000
1             1344    2. < 1000-2000
2              936         1. < 1000
3             1393    2. < 1000-2000
4              776         1. < 1000
..             ...               ...
995           2600    3. < 2000-3000
996           4455        4. >= 3000
997           6403        4. >= 3000
998           5003        4. >= 3000
999           1804    2. < 1000-2000

[1000 rows x 2 columns]

In [ ]:
sql = '''select
case
when t.credit_amount < 1000 then '1. < 1000'
when t.credit_amount < 2000 then '2. 1000-2000'
when t.credit_amount < 3000 then '3. 2000-3000'
when t.credit_amount >= 3000 then '4. >= 3000'

else 'other' end as credit_amount_bin,

count(1) as credit_cnt

  from german_credit t
  group by 1
 '''

In [ ]:
select(sql)

  credit_amount_bin  credit_cnt
0         1. < 1000         116
1      2. 1000-2000         316
2      3. 2000-3000         188
3        4. >= 3000         380

## Столбцы сводной таблицы

In [ ]:
sql = '''select t.housing,
count(case when t.sex = 'female' then 1 else null end) as female,
count(case when t.sex = 'male' then 1 else null end) as male,

count(1) as cnt

from german_credit t
group by t.housing
 '''

In [ ]:
select(sql)

  housing  female  male  cnt
0    free      19    89  108
1     own     196   517  713
2    rent      95    84  179

In [ ]:
sql = '''select distinct t.purpose from german_credit t '''

In [ ]:
purpose = list(select(sql)['purpose'].values)

In [ ]:
purpose

['radio/TV',
 'car',
 'education',
 'furniture/equipment',
 'repairs',
 'business',
 'domestic appliances',
 'vacation/others']

In [ ]:
for p in purpose:
  print(f"count(case when t.purpose = '{p}' then 1 else null end) as {p.lower().replace(' ','').replace('/','')},")

count(case when t.purpose = 'radio/TV' then 1 else null end) as radiotv,
count(case when t.purpose = 'car' then 1 else null end) as car,
count(case when t.purpose = 'education' then 1 else null end) as education,
count(case when t.purpose = 'furniture/equipment' then 1 else null end) as furnitureequipment,
count(case when t.purpose = 'repairs' then 1 else null end) as repairs,
count(case when t.purpose = 'business' then 1 else null end) as business,
count(case when t.purpose = 'domestic appliances' then 1 else null end) as domesticappliances,
count(case when t.purpose = 'vacation/others' then 1 else null end) as vacationothers,

In [ ]:
sql = '''select t.housing,

count(case when t.purpose = 'radio/TV' then 1 else null end) as radiotv,
count(case when t.purpose = 'car' then 1 else null end) as car,
count(case when t.purpose = 'education' then 1 else null end) as education,
count(case when t.purpose = 'furniture/equipment' then 1 else null end) as furnitureequipment,
count(case when t.purpose = 'repairs' then 1 else null end) as repairs,
count(case when t.purpose = 'business' then 1 else null end) as business,
count(case when t.purpose = 'domestic appliances' then 1 else null end) as domesticappliances,
count(case when t.purpose = 'vacation/others' then 1 else null end) as vacationothers,
count(1) as cnt

from german_credit t
group  by t.housing'''

In [ ]:
select(sql)

,housing,radiotv,car,education,furnitureequipment,repairs,business,domesticappliances,vacationothers,cnt
0,free,15,55,15,11,3,5,0,4,108
1,own,227,219,34,122,17,76,10,8,713
2,rent,38,63,10,48,2,16,2,0,179

## Категории из текстовых данных

In [ ]:
t = pd.DataFrame({'purpose':['машина','машина','машина','на машину','на покупку машины',
                             'автомобиль','на возвращение 2007',
                             'на свадьбу','свадьба','свадьба','свадьба','для свадьбы',
                             'недвижимость','на покупку недвижимости']})

In [ ]:
t

                    purpose
0                    машина
1                    машина
2                    машина
3                 на машину
4         на покупку машины
5                автомобиль
6       на возвращение 2007
7                на свадьбу
8                   свадьба
9                   свадьба
10                  свадьба
11              для свадьбы
12             недвижимость
13  на покупку недвижимости

In [ ]:
t.to_sql('purpose',con,index=False,if_exists='replace')

14

In [ ]:
df.head()

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id,client_id_2
0,33,male,2,own,NaN,NaN,3074,9,radio/TV,0,2008-06-29 18:52:00,210,245
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929,391
2,52,male,2,own,quite rich,NaN,936,9,education,0,2008-04-27 08:23:07,200,544
3,35,female,3,own,little,NaN,1393,11,car,0,2007-05-06 10:58:22,45,596
4,28,male,2,own,little,NaN,776,12,radio/TV,0,2007-07-21 13:22:14,358,373

In [ ]:
sql = '''select * from purpose t'''

In [ ]:
select(sql)

                    purpose
0                    машина
1                    машина
2                    машина
3                 на машину
4         на покупку машины
5                автомобиль
6       на возвращение 2007
7                на свадьбу
8                   свадьба
9                   свадьба
10                  свадьба
11              для свадьбы
12             недвижимость
13  на покупку недвижимости

In [ ]:
sql = '''select t.purpose, count(1) from purpose t
group by t.purpose
order by count(1) desc
'''

In [ ]:
select(sql)

                   purpose  count(1)
0                  свадьба         3
1                   машина         3
2             недвижимость         1
3               на свадьбу         1
4  на покупку недвижимости         1
5        на покупку машины         1
6                на машину         1
7      на возвращение 2007         1
8              для свадьбы         1
9               автомобиль         1

In [ ]:
cat = '''select t.purpose,

case when t.purpose like '%свадьб%' then 'свадьба'
when t.purpose like '%машин%' or t.purpose like '%авто%' then 'машина'
when t.purpose like '%недвиж%' then 'недвижимость'

else 'другое' end as purpose_cat

  from purpose t'''

In [ ]:
select(cat)

                    purpose   purpose_cat
0                    машина        машина
1                    машина        машина
2                    машина        машина
3                 на машину        машина
4         на покупку машины        машина
5                автомобиль        машина
6       на возвращение 2007        другое
7                на свадьбу       свадьба
8                   свадьба       свадьба
9                   свадьба       свадьба
10                  свадьба       свадьба
11              для свадьбы       свадьба
12             недвижимость  недвижимость
13  на покупку недвижимости  недвижимость

In [ ]:
sql = f'''select
t.purpose_cat,

count(1)

  from ({cat}) t
  group by t.purpose_cat'''

In [ ]:
select(sql)

    purpose_cat  count(1)
0        другое         1
1        машина         6
2  недвижимость         2
3       свадьба         5

In [ ]:
sql = f'''select t.purpose, count(1)

from ({cat}) t
where t.purpose_cat = 'другое'

group by t.purpose

order by count(1) desc
'''

In [ ]:
select(sql)

               purpose  count(1)
0  на возвращение 2007         1

# Подзапросы

## Обычный подзапрос

In [ ]:
t = pd.DataFrame({'id':[1,1,2,2,3],'name':['a','b','c','d','e']})

In [ ]:
t

   id name
0   1    a
1   1    b
2   2    c
3   2    d
4   3    e

In [ ]:
t.to_sql('dupl_test',con,index=False,if_exists='replace')

5

In [ ]:
sql = '''select * from dupl_test t'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d
4   3    e

In [ ]:
sql = '''select t.id from dupl_test t
group by t.id
having count(1) > 1'''

In [ ]:
select(sql)

   id
0   1
1   2

In [ ]:
sql = '''select * from dupl_test t
where t.id in (select t.id from dupl_test t
group by t.id
having count(1) > 1)'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d

In [ ]:
sql = '''
drop table if exists dupls;
create table dupls as
select t.id from dupl_test t
group by t.id
having count(1) > 1'''

In [ ]:
cur.executescript(sql)

In [ ]:
sql = '''select * from dupls t'''

In [ ]:
select(sql)

   id
0   1
1   2

In [ ]:
sql = '''select * from dupl_test t
where t.id in dupls'''

In [ ]:
select(sql)

   id name
0   1    a
1   1    b
2   2    c
3   2    d

In [ ]:
sql = '''
select * from

(select t.id, count(1) as cnt from dupl_test t
group by t.id) t

where t.cnt > 1

 '''

In [ ]:
select(sql)

   id  cnt
0   1    2
1   2    2

## CTE (with)

In [ ]:
sql = '''
select * from (

select * from

(select t.id, count(1) as cnt from dupl_test t
group by t.id) t

where t.cnt > 1) t

where t.id = 1 '''

In [ ]:
select(sql)

   id  cnt
0   1    2

In [ ]:
sql = '''
with id_cnt as (
select t.id, count(1) as cnt from dupl_test t
group by t.id),

id_cnt_2 as

(select * from id_cnt t
where t.cnt > 1)

select * from id_cnt_2 t
where t.id = 1 '''

In [ ]:
select(sql)

   id  cnt
0   1    2

In [ ]:
sql = f'''select
t.purpose_cat,

count(1)

  from ({cat}) t
  group by t.purpose_cat '''

In [ ]:
print(sql)

select
t.purpose_cat,

count(1)

  from (select t.purpose,

case when t.purpose like '%свадьб%' then 'свадьба'
when t.purpose like '%машин%' or t.purpose like '%авто%' then 'машина'
when t.purpose like '%недвиж%' then 'недвижимость'

else 'другое' end as purpose_cat

  from purpose t) t
  group by t.purpose_cat

In [ ]:
sql = '''
with categories as (
select t.purpose,

case when t.purpose like '%свадьб%' then 'свадьба'
when t.purpose like '%машин%' or t.purpose like '%авто%' then 'машина'
when t.purpose like '%недвиж%' then 'недвижимость'

else 'другое' end as purpose_cat

  from purpose t)

  select t.purpose_cat,

  count(1) from categories t
  group by t.purpose_cat '''

In [ ]:
select(sql)

    purpose_cat  count(1)
0        другое         1
1        машина         6
2  недвижимость         2
3       свадьба         5

## Когда лучше создавать таблицу

In [ ]:
sql = '''
drop table if exists categories;
create table categories as
select t.purpose,

case when t.purpose like '%свадьб%' then 'свадьба'
when t.purpose like '%машин%' or t.purpose like '%авто%' then 'машина'
when t.purpose like '%недвиж%' then 'недвижимость'

else 'другое' end as purpose_cat

 from purpose t'''

In [ ]:
cur.executescript(sql)

In [ ]:
sql = '''select * from categories t'''

In [ ]:
select(sql)

                    purpose   purpose_cat
0                    машина        машина
1                    машина        машина
2                    машина        машина
3                 на машину        машина
4         на покупку машины        машина
5                автомобиль        машина
6       на возвращение 2007        другое
7                на свадьбу       свадьба
8                   свадьба       свадьба
9                   свадьба       свадьба
10                  свадьба       свадьба
11              для свадьбы       свадьба
12             недвижимость  недвижимость
13  на покупку недвижимости  недвижимость

In [ ]:
sql = f'''select
t.purpose_cat,

count(1)

from categories t
group by t.purpose_cat'''

In [ ]:
select(sql)

    purpose_cat  count(1)
0        другое         1
1        машина         6
2  недвижимость         2
3       свадьба         5

In [ ]:
sql = '''select t.purpose, count(1)

from categories t
where t.purpose_cat = 'другое'


group by t.purpose

order by count(1) desc'''

In [ ]:
select(sql)

               purpose  count(1)
0  на возвращение 2007         1

In [ ]:
sql = '''
with categories as (
select 1

from purpose t)

select * from categories t
'''

In [ ]:
select(sql)

    1
0   1
1   1
2   1
3   1
4   1
5   1
6   1
7   1
8   1
9   1
10  1
11  1
12  1
13  1

# Джойны

## Лефт и иннер джойн

In [ ]:
sql = '''select * from german_credit t limit 5 '''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,None,776,12,radio/TV,0,2007-07-21 13:22:14,358

In [ ]:
users = pd.DataFrame({'id':[1,2,3],'name':['gleb','jon snow','tyrion']})

In [ ]:
users

   id      name
0   1      gleb
1   2  jon snow
2   3    tyrion

In [ ]:
items = pd.DataFrame({'user_id':[1,3,3], 'item_name':['hleb','gold', 'wine'],'value':[5,100,20]})

In [ ]:
items

   user_id item_name  value
0        1      hleb      5
1        3      gold    100
2        3      wine     20

In [ ]:
users.to_sql('users',con,index=False,if_exists='replace')
items.to_sql('items',con,index=False,if_exists='replace')

3

In [ ]:
sql = '''select t.*, i.item_name, i.value, i.user_id from users t
left join items i on t.id = i.user_id
'''

In [ ]:
select(sql)

   id      name item_name  value  user_id
0   1      gleb      hleb    5.0      1.0
1   2  jon snow      None    NaN      NaN
2   3    tyrion      gold  100.0      3.0
3   3    tyrion      wine   20.0      3.0

In [ ]:
sql = '''select t.*, i.item_name from users t
join items i on t.id = i.user_id
'''

In [ ]:
select(sql)

   id    name item_name
0   1    gleb      hleb
1   3  tyrion      gold
2   3  tyrion      wine

In [ ]:
sql = '''select t.*, i.item_name from users t
left join items i on t.id = i.user_id
where i.item_name is not null
'''

In [ ]:
select(sql)

   id    name item_name
0   1    gleb      hleb
1   3  tyrion      gold
2   3  tyrion      wine

## Агрегируй перед тем как джойнить

In [ ]:
users = pd.DataFrame({'id':[1,2,3], 'name':['gleb','jon snow','tyrion'], 'victory':[2,10,1]})

In [ ]:
users

   id      name  victory
0   1      gleb        2
1   2  jon snow       10
2   3    tyrion        1

In [ ]:
users.to_sql('users',con,index=False,if_exists='replace')

3

In [ ]:
sql = '''select t.*, i.item_name, i.value, i.user_id from users t
left join items i on t.id = i.user_id'''

In [ ]:
t = select(sql)

Задубливание по tyrion (двойной счет, побед должно быть 2+10+1=13)

In [ ]:
t

   id      name  victory item_name  value  user_id
0   1      gleb        2      hleb    5.0      1.0
1   2  jon snow       10      None    NaN      NaN
2   3    tyrion        1      gold  100.0      3.0
3   3    tyrion        1      wine   20.0      3.0

In [ ]:
t['victory'].sum()

np.int64(14)

In [ ]:
sql = '''select sum (t.victory) from users t '''

In [ ]:
select(sql)

   sum (t.victory)
0               13

Если использовать иннер джойн тоже не правильно

In [ ]:
sql = '''select t.*, i.item_name, i.value, i.user_id from users t
join items i on t.id = i.user_id
'''

In [ ]:
select(sql)

   id    name  victory item_name  value  user_id
0   1    gleb        2      hleb      5        1
1   3  tyrion        1      gold    100        3
2   3  tyrion        1      wine     20        3

Кажется праивльно, но так делать плохо:

In [ ]:
sql = '''select t.id, t.name,
t.victory,
count(i.item_name) as item_cnt,
coalesce(sum(i.value),0) as value_sum

from users t
left join items i on t.id = i.user_id
group by t.id, t.name, t.victory
'''

In [ ]:
select(sql)

   id      name  victory  item_cnt  value_sum
0   1      gleb        2         1          5
1   2  jon snow       10         0          0
2   3    tyrion        1         2        120

С агрегируй данные перед тем как джойнить

In [ ]:
sql = '''select t.user_id, count(t.item_name) as item_cnt,
sum(value) as value_sum from items t
group by t.user_id'''

Теперь юзеры уникальны потому что на них сгрупировали

In [ ]:
select(sql)

   user_id  item_cnt  value_sum
0        1         1          5
1        3         2        120

Теперь джойним эту таблицу

In [ ]:
sql = '''
with items_agg as (

select t.user_id, count(t.item_name) as item_cnt,
sum(value) as value_sum from items t
group by t.user_id)

select t.id, t.name,
t.victory,

coalesce(i.item_cnt,0) as item_cnt,
coalesce(i.value_sum,0) as value_sum

from users t

left join items_agg i on t.id = i.user_id

'''

In [ ]:
select(sql)

   id      name  victory  item_cnt  value_sum
0   1      gleb        2         1          5
1   2  jon snow       10         0          0
2   3    tyrion        1         2        120

## Inner joun

In [ ]:
sql = '''select * from german_credit t
limit 5 '''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,None,776,12,radio/TV,0,2007-07-21 13:22:14,358

In [ ]:
clients = pd.DataFrame({'client_id':[200,45], 'data':[1,2]})

In [ ]:
clients.to_sql('cliets_task_name',con,index=False,if_exists='replace')

2

In [ ]:
sql = '''select t.*, ctn.data from german_credit t
join cliets_task_name ctn on t.client_id = ctn.client_id '''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id,data
0,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200,1
1,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45,2

In [ ]:
sql = ''' select 1 as user_id
union all
select 2 as user_id
union all
select 3 as user_id'''

In [ ]:
select(sql)

   user_id
0        1
1        2
2        3

In [ ]:
sql = '''select date('2021-03-01') as month
union all
select date ('2021-04-01') as month'''

In [ ]:
select(sql)

        month
0  2021-03-01
1  2021-04-01

Это запрос строит декартово произведение (все возможные пары).
Как он работает по шагам
1. CTE users — создаёт временный набор из трёх строк: user_id = 1, 2, 3.
2. CTE month — создаёт временный набор из двух строк: month = '2021-03-01' и '2021-04-01'.
3. JOIN ... ON 1=1 — это хитрый приём: условие 1=1 всегда истинно, поэтому каждая строка из users соединяется с каждой строкой из month.

Зачем так делают
1. Создать «сетку» для отчётов. Например, чтобы для каждого пользователя получить строку за каждый месяц — даже если в реальных данных за какой‑то месяц записей нет. Потом к этой сетке можно присоединить фактические данные через LEFT JOIN и увидеть пропуски.
2. Подготовить шаблон для агрегаций. Удобно, когда нужно явно иметь все комбинации категорий, чтобы корректно посчитать метрики по всем срезам.
3. Тестирование логики. Как и в прошлом примере, это быстрый способ получить небольшой детерминированный набор данных для проверки запроса.

Важное уточнение
1. Это не создаёт таблиц в базе — оба CTE (users и month) существуют только в рамках выполнения этого запроса.

In [ ]:
sql = '''
with users as(
select 1 as user_id
union all
select 2 as user_id
union all
select 3 as user_id),

mont as

(select date('2021-03-01') as month
union all
select date ('2021-04-01') as month)

select * from users t
join month m on 1=1

'''

In [ ]:
select(sql)

   user_id       month
0        1  2021-03-01
1        2  2021-03-01
2        3  2021-03-01
3        1  2021-04-01
4        2  2021-04-01
5        3  2021-04-01

## Ежемесячный отчет

In [ ]:
sql = '''select * from german_credit t
limit 5'''

In [ ]:
select(sql)

,age,sex,job,housing,saving_accounts,checking_account,credit_amount,duration,purpose,default,contract_dt,client_id
0,33,male,2,own,None,None,3074,9,radio/TV,0,2008-06-29 18:52:00,210
1,43,male,1,own,little,little,1344,12,car,0,2007-05-20 18:30:19,929
2,52,male,2,own,quite rich,None,936,9,education,0,2008-04-27 08:23:07,200
3,35,female,3,own,little,None,1393,11,car,0,2007-05-06 10:58:22,45
4,28,male,2,own,little,None,776,12,radio/TV,0,2007-07-21 13:22:14,358

https://drive.google.com/file/d/1ksjv4EsLItdn9rYA4oxislish-c4eE4D/view?usp=sharing

In [ ]:
! gdown --id 1ksjv4EsLItdn9rYA4oxislish-c4eE4D

/usr/local/lib/python3.13/dist-packages/gdown/__main__.py:139: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Downloading...
From: https://drive.google.com/uc?id=1ksjv4EsLItdn9rYA4oxislish-c4eE4D
To: /content/german_credit_augmented_transactions.csv
100% 134k/134k [00:00<00:00, 67.8MB/s]

In [ ]:
transactions = pd.read_csv('/content/german_credit_augmented_transactions.csv')

In [ ]:
transactions.head()

                    dt  client_id  amount
0  2008-04-06 11:54:47        950  161.38
1  2007-07-28 00:00:19        418   35.34
2  2008-03-14 20:43:54        131  146.50
3  2007-12-18 13:03:24        353  119.21
4  2007-11-09 05:18:30        849  105.24

In [ ]:
transactions.to_sql('client_transactions',con,index=False,if_exists='replace')

4275

In [ ]:
sql = '''select * from client_transactions t limit 5'''

In [ ]:
select(sql)

                    dt  client_id  amount
0  2008-04-06 11:54:47        950  161.38
1  2007-07-28 00:00:19        418   35.34
2  2008-03-14 20:43:54        131  146.50
3  2007-12-18 13:03:24        353  119.21
4  2007-11-09 05:18:30        849  105.24

In [ ]:
sql = '''select count(*) from client_transactions t'''

In [ ]:
select(sql)

   count(*)
0      4275

In [ ]:
sql = '''select
date(t.dt, 'start of month') as month,
count(1) as transaction_cnt,
sum(t.amount) as amount_sum

 from client_transactions t
group by 1
order by 1
'''

In [ ]:
select(sql)

         month  transaction_cnt  amount_sum
0   2007-05-01              338   450912.77
1   2007-06-01              379   551664.83
2   2007-07-01              304   494134.50
3   2007-08-01              255   426903.23
4   2007-10-01              332   634846.49
5   2007-11-01              389   500420.98
6   2007-12-01              364   561449.89
7   2008-01-01              413   630137.22
8   2008-02-01              228   337043.47
9   2008-03-01              309   425599.09
10  2008-04-01              383   677194.97
11  2008-05-01              310   474962.34
12  2008-06-01              271   383710.84

In [ ]:
min = '''select date(min(t.dt),'start of month') from client_transactions t'''

In [ ]:
max = '''select date(max(t.dt),'start of month') from client_transactions t'''

In [ ]:
select(max)

  date(max(t.dt),'start of month')
0                       2008-06-01

In [ ]:
sql = f'''WITH RECURSIVE dates(month) AS (
  VALUES(({min}))
  UNION ALL
  SELECT date(month, '+1 month')
  FROM dates
  WHERE month < ({max})
)
SELECT t.month FROM dates t'''

In [ ]:
select(sql)

         month
0   2007-05-01
1   2007-06-01
2   2007-07-01
3   2007-08-01
4   2007-09-01
5   2007-10-01
6   2007-11-01
7   2007-12-01
8   2008-01-01
9   2008-02-01
10  2008-03-01
11  2008-04-01
12  2008-05-01
13  2008-06-01

In [ ]:
sql = f'''WITH dates(month) AS (
  VALUES(({min}))
  UNION ALL
  SELECT date(month, '+1 month')
  FROM dates
  WHERE month < ({max})
),
trans_month as

(select
date(t.dt, 'start of month') as month,
count(1) as transaction_cnt,
sum(t.amount) as amount_sum

 from client_transactions t
group by 1
order by 1)


SELECT t.month,
coalesce(tm.transaction_cnt,0) as transaction_cnt,
coalesce(tm.amount_sum,0) as amount_sum

FROM dates t
left join trans_month tm on t.month = tm.month
order by t.month'''

In [ ]:
select(sql)

         month  transaction_cnt  amount_sum
0   2007-05-01              338   450912.77
1   2007-06-01              379   551664.83
2   2007-07-01              304   494134.50
3   2007-08-01              255   426903.23
4   2007-09-01                0        0.00
5   2007-10-01              332   634846.49
6   2007-11-01              389   500420.98
7   2007-12-01              364   561449.89
8   2008-01-01              413   630137.22
9   2008-02-01              228   337043.47
10  2008-03-01              309   425599.09
11  2008-04-01              383   677194.97
12  2008-05-01              310   474962.34
13  2008-06-01              271   383710.84

## Ежемесячный отчет на пользователя

In [ ]:
sql = '''select distinct t.client_id from german_credit t '''

In [ ]:
select(sql)

     client_id
0          210
1          929
2          200
3           45
4          358
..         ...
995        624
996        181
997        730
998        557
999         23

[1000 rows x 1 columns]

In [ ]:
sql = '''select
date(t.dt, 'start of month') as month,
t.client_id,
count(1) as transaction_cnt,
sum(t.amount) as amount_sum

from client_transaction t
group by 1,2
order by 1 '''

In [ ]:
select(sql)

           month  client_id  transaction_cnt  amount_sum
0     2007-05-01        101                1      149.67
1     2007-05-01        107                2      217.50
2     2007-05-01        110                1     1081.32
3     2007-05-01        111                1      139.97
4     2007-05-01        113                1     1051.29
...          ...        ...              ...         ...
3551  2008-06-01        983                1    10050.37
3552  2008-06-01        987                1      192.48
3553  2008-06-01        992                1     -610.21
3554  2008-06-01        996                1      121.28
3555  2008-06-01        999                1     -641.25

[3556 rows x 4 columns]

In [ ]:
sql = f'''WITH dates(month) AS (
  VALUES(({min}))
  UNION ALL
  SELECT date(month, '+1 month')
  FROM dates
  WHERE month < ({max})
),

clients as (select distinct t.client_id from german_credit t),

clients_month as

(SELECT t.month, c.client_id FROM dates t
join clients c on 1=1),

trans_month as

(select
date(t.dt, 'start of month') as month,
t.client_id,
count(1) as transaction_cnt,
sum(t.amount) as amount_sum

 from client_transactions t
group by 1,2
order by 1),

client_trans_month as (

select t.*,
tm.transaction_cnt,
tm.amount_sum,
1 as user,
case when tm.transaction_cnt > 0 then 1 else 0 end as active

 from clients_month t
left join trans_month tm on t.client_id = tm.client_id
and t.month = tm.month
)

select t.month, sum(t.user) as user_cnt, sum(t.amount_sum) as amount_sum ,
sum(t.active) as active_cnt from client_trans_month t
group by t.month
'''

In [ ]:
t = select(sql)

In [ ]:
sql = '''select sum(t.amount) from client_transactions t'''

In [ ]:
select(sql)

   sum(t.amount)
0     6548980.62

In [ ]:
t['amount_sum'].sum()

np.float64(6548980.619999999)

In [ ]:
t

         month  user_cnt  amount_sum  active_cnt
0   2007-05-01      1000   450912.77         288
1   2007-06-01      1000   551664.83         297
2   2007-07-01      1000   494134.50         259
3   2007-08-01      1000   426903.23         222
4   2007-09-01      1000         NaN           0
5   2007-10-01      1000   634846.49         283
6   2007-11-01      1000   500420.98         323
7   2007-12-01      1000   561449.89         287
8   2008-01-01      1000   630137.22         325
9   2008-02-01      1000   337043.47         204
10  2008-03-01      1000   425599.09         267
11  2008-04-01      1000   677194.97         301
12  2008-05-01      1000   474962.34         263
13  2008-06-01      1000   383710.84         237

In [ ]:
2 * 365 * 10000

7300000

## Джойн таблицы самой на себя (нарастающий итог)

In [ ]:
t = pd.DataFrame({'dt':pd.to_datetime(['2021-04-01','2021-04-02','2021-04-03'],format='%Y-%m-%d'),
                  'revenue':[1,2,3]})

In [ ]:
t

          dt  revenue
0 2021-04-01        1
1 2021-04-02        2
2 2021-04-03        3

In [ ]:
t.to_sql('revenue',con,index=False,if_exists='replace')

3

In [ ]:
sql = '''select
t.dt, t.revenue, sum(r.revenue) as cumsum from revenue t
join revenue r on r.dt >= t.dt
group by t.dt, t.revenue '''

In [ ]:
select(sql)

                    dt  revenue  cumsum
0  2021-04-01 00:00:00        1       6
1  2021-04-02 00:00:00        2       5
2  2021-04-03 00:00:00        3       3