<a href="https://colab.research.google.com/github/ksmorozov7/Portfolio/blob/main/SQL_EMP_DEPT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Заливка данных

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import sqlite3

In [ ]:
sqlite3.sqlite_version

'3.45.1'

In [ ]:
! ls '/content/drive/My Drive/data'

emp_dept.db		     german_credit_augmented_transactions.csv
german_credit_augmented.csv  german_credit.db

In [ ]:
con = sqlite3.connect('/content/drive/My Drive/data/emp_dept.db')

## Функция для работы select

In [ ]:
def select(sql):
  return pd.read_sql(sql,con)

## Функция для работы
- DDL — Data Definition Language (меняет структуру);
- DML — Data Manipulation Language (меняет данные);
- DCL/TCL — управление транзакциями (реже)

In [ ]:
def execute(sql):
    cur = con.cursor()
    cur.execute(sql)
    con.commit()

## Таблицы

In [ ]:
df_dept = pd.DataFrame({'DEPTNO':[10,20,30,40],
                  'DNAME':['ACCOUNTING','RESEARCH','SALES','OPERATIONS'],
                  'LOC':['NEW YORK','DALLAS','CHICAGO','BOSTON']})

In [ ]:
df_dept

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [ ]:
df_dept.to_sql('DEPT',con,index=False,if_exists='replace')

4

In [ ]:
sql = '''select * from DEPT t'''

In [ ]:
select(sql)

   DEPTNO       DNAME       LOC
0      10  ACCOUNTING  NEW YORK
1      20    RESEARCH    DALLAS
2      30       SALES   CHICAGO
3      40  OPERATIONS    BOSTON

In [ ]:
df_emp = pd.DataFrame({'EMPNO':[7369,7499,7521,7566,7654,7698,7782,7788,7839,7844,7876,7900,7902,7934],
                  'ENAME':['SMITH','ALLEN','WARD','JONES','MARTIN','BLAKE','CLARK','SCOTT','KING','TURNER','ADAMS','JAMES','FORD','MILLER'],
                  'JOB':['CLERK','SALESMAN','SALESMAN','MANAGER','SALESMAN','MANAGER','MANAGER','ANALYST','PRESIDENT','SALESMAN','CLERK','CLERK','ANALYST','CLERK'],
                  'MGR':[7902,7698,7698,7839,7698,7839,7839,7566,np.nan,7698,7788,7698,7566,7782],
                  'HIREDATE':['17-DEC-1980','20-FEB-1981','22-FEB-1981','02-APR-1981','28-SEP-1981','01-MAY-1981','09-JUN-1981','09-DEC-1982','17-NOV-1981','08-SEP-1981','12-JAN-1983','03-DEC-1981','03-DEC-1981','23-JAN-1982'],
                  'SAL':[800,1600,1250,2975,1250,2850,2450,3000,5000,1500,1100,950,3000,1300],
                  'COMM':[np.nan,300,500,np.nan,1400,np.nan,np.nan,np.nan,np.nan,0,np.nan,np.nan,np.nan,np.nan],
                  'DEPTNO':[20,30,30,20,30,30,10,20,10,30,20,30,20,10]})

In [ ]:
df_emp

    EMPNO   ENAME        JOB     MGR     HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0  17-DEC-1980   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0  20-FEB-1981  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0  22-FEB-1981  1250   500.0      30
3    7566   JONES    MANAGER  7839.0  02-APR-1981  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0  28-SEP-1981  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0  01-MAY-1981  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0  09-JUN-1981  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0  09-DEC-1982  3000     NaN      20
8    7839    KING  PRESIDENT     NaN  17-NOV-1981  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0  08-SEP-1981  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0  12-JAN-1983  1100     NaN      20
11   7900   JAMES      CLERK  7698.0  03-DEC-1981   950     NaN      30
12   7902    FORD    ANALYST  7566.0  03-DEC-1981  3000     NaN      20
13   7934  MILLER      CLERK  7782.0  23-JAN-1982  1300     NaN      10

In [ ]:
df_emp['HIREDATE'] = pd.to_datetime(df_emp['HIREDATE'],format='%d-%b-%Y')

In [ ]:
df_emp.dtypes

EMPNO                int64
ENAME               object
JOB                 object
MGR                float64
HIREDATE    datetime64[ns]
SAL                  int64
COMM               float64
DEPTNO               int64
dtype: object

In [ ]:
df_emp.to_sql('EMP',con,index=False,if_exists='replace')

14

In [ ]:
sql = '''select * from EMP t'''

In [ ]:
select(sql)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
0,7369,SMITH,CLERK,7902.0,1980-12-17 00:00:00,800,NaN,20
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20 00:00:00,1600,300.0,30
2,7521,WARD,SALESMAN,7698.0,1981-02-22 00:00:00,1250,500.0,30
3,7566,JONES,MANAGER,7839.0,1981-04-02 00:00:00,2975,NaN,20
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28 00:00:00,1250,1400.0,30
5,7698,BLAKE,MANAGER,7839.0,1981-05-01 00:00:00,2850,NaN,30
6,7782,CLARK,MANAGER,7839.0,1981-06-09 00:00:00,2450,NaN,10
7,7788,SCOTT,ANALYST,7566.0,1982-12-09 00:00:00,3000,NaN,20
8,7839,KING,PRESIDENT,NaN,1981-11-17 00:00:00,5000,NaN,10
9,7844,TURNER,SALESMAN,7698.0,1981-09-08 00:00:00,1500,0.0,30
10,7876,ADAMS,CLERK,7788.0,1983-01-12 00:00:00,1100,NaN,20
11,7900,JAMES,CLERK,7698.0,1981-12-03 00:00:00,950,NaN,30
12,7902,FORD,ANALYST,7566.0,1981-12-03 00:00:00,3000,NaN,20
13,7934,MILLER,CLERK,7782.0,1982-01-23 00:00:00,1300,NaN,10

# Select

## Псевдонимы

In [ ]:
sql = '''select t.EMPNO, t.ENAME, t.SAL, t.SAL * 2 AS SAL_NEW
from EMP as t limit 5'''

In [ ]:
select(sql)

   EMPNO   ENAME   SAL  SAL_NEW
0   7369   SMITH   800     1600
1   7499   ALLEN  1600     3200
2   7521    WARD  1250     2500
3   7566   JONES  2975     5950
4   7654  MARTIN  1250     2500

## Манипуляции со столбцами

In [ ]:
sql = '''select t.*,
t.SAL * 3 as SAL_mult3,
t.SAL + t.SAL as SUM_SAL
from EMP as t limit 5
 '''

In [ ]:
select(sql)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO,SAL_mult3,SUM_SAL
0,7369,SMITH,CLERK,7902.0,1980-12-17 00:00:00,800,NaN,20,2400,1600
1,7499,ALLEN,SALESMAN,7698.0,1981-02-20 00:00:00,1600,300.0,30,4800,3200
2,7521,WARD,SALESMAN,7698.0,1981-02-22 00:00:00,1250,500.0,30,3750,2500
3,7566,JONES,MANAGER,7839.0,1981-04-02 00:00:00,2975,NaN,20,8925,5950
4,7654,MARTIN,SALESMAN,7698.0,1981-09-28 00:00:00,1250,1400.0,30,3750,2500

## Where

In [ ]:
df_emp.head()

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0 1980-12-17   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0 1981-02-22  1250   500.0      30
3   7566   JONES   MANAGER  7839.0 1981-04-02  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250  1400.0      30

In [ ]:
sql = '''select * from EMP e limit 5'''

In [ ]:
select(sql)

   EMPNO   ENAME       JOB     MGR             HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0  1980-12-17 00:00:00   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0  1981-02-20 00:00:00  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0  1981-02-22 00:00:00  1250   500.0      30
3   7566   JONES   MANAGER  7839.0  1981-04-02 00:00:00  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0  1981-09-28 00:00:00  1250  1400.0      30

In [ ]:
sql = '''select count(1) from EMP e
where e.HIREDATE between '1980-12-17' and '2000-02-20'
'''

In [ ]:
select(sql)

   count(1)
0        14

In [ ]:
sql = '''select * from EMP e
where e.HIREDATE between '1980-12-17' and '1982-02-20'
and e.JOB in ('CLERK','SALESMAN')
order by e.HIREDATE desc
'''

In [ ]:
select(sql)

   EMPNO   ENAME       JOB     MGR             HIREDATE   SAL    COMM  DEPTNO
0   7934  MILLER     CLERK  7782.0  1982-01-23 00:00:00  1300     NaN      10
1   7900   JAMES     CLERK  7698.0  1981-12-03 00:00:00   950     NaN      30
2   7654  MARTIN  SALESMAN  7698.0  1981-09-28 00:00:00  1250  1400.0      30
3   7844  TURNER  SALESMAN  7698.0  1981-09-08 00:00:00  1500     0.0      30
4   7521    WARD  SALESMAN  7698.0  1981-02-22 00:00:00  1250   500.0      30
5   7499   ALLEN  SALESMAN  7698.0  1981-02-20 00:00:00  1600   300.0      30
6   7369   SMITH     CLERK  7902.0  1980-12-17 00:00:00   800     NaN      20

## Like

In [ ]:
df_emp.head()

   EMPNO   ENAME       JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0   7369   SMITH     CLERK  7902.0 1980-12-17   800     NaN      20
1   7499   ALLEN  SALESMAN  7698.0 1981-02-20  1600   300.0      30
2   7521    WARD  SALESMAN  7698.0 1981-02-22  1250   500.0      30
3   7566   JONES   MANAGER  7839.0 1981-04-02  2975     NaN      20
4   7654  MARTIN  SALESMAN  7698.0 1981-09-28  1250  1400.0      30

In [ ]:
sql = '''select * from EMP e
where (e.JOB like '%CLE%'
or e.JOB like '%CL%') and e.SAL > 1000
'''

In [ ]:
select(sql)

   EMPNO   ENAME    JOB     MGR             HIREDATE   SAL  COMM  DEPTNO
0   7876   ADAMS  CLERK  7788.0  1983-01-12 00:00:00  1100  None      20
1   7934  MILLER  CLERK  7782.0  1982-01-23 00:00:00  1300  None      10

In [ ]:
sql = '''select count(*) from EMP e'''

In [ ]:
select(sql)

   count(*)
0        14

In [ ]:
sql = '''select count(*) from EMP e
where SAL > 1000'''

In [ ]:
select(sql)

   count(*)
0        12

In [ ]:
12/14

0.8571428571428571

In [ ]:
sql = '''select e.SAL,
case when e.SAL > 1000 then 1 else 0 end as greater_1000_flag,

iif(e.SAL > 1000,1,0) as greater_1000_flag2

from EMP e '''

In [ ]:
select(sql)

     SAL  greater_1000_flag  greater_1000_flag2
0    800                  0                   0
1   1600                  1                   1
2   1250                  1                   1
3   2975                  1                   1
4   1250                  1                   1
5   2850                  1                   1
6   2450                  1                   1
7   3000                  1                   1
8   5000                  1                   1
9   1500                  1                   1
10  1100                  1                   1
11   950                  0                   0
12  3000                  1                   1
13  1300                  1                   1

In [ ]:
sql = '''select
avg(case when e.SAL > 1000 then 1 else 0 end) as greater_1000_frac
from EMP e'''

In [ ]:
select(sql)

   greater_1000_frac
0           0.857143

## Crate table

In [ ]:
sql = '''select * from EMP e
where e.SAL > 1000'''

In [ ]:
select(sql)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
0,7499,ALLEN,SALESMAN,7698.0,1981-02-20 00:00:00,1600,300.0,30
1,7521,WARD,SALESMAN,7698.0,1981-02-22 00:00:00,1250,500.0,30
2,7566,JONES,MANAGER,7839.0,1981-04-02 00:00:00,2975,NaN,20
3,7654,MARTIN,SALESMAN,7698.0,1981-09-28 00:00:00,1250,1400.0,30
4,7698,BLAKE,MANAGER,7839.0,1981-05-01 00:00:00,2850,NaN,30
5,7782,CLARK,MANAGER,7839.0,1981-06-09 00:00:00,2450,NaN,10
6,7788,SCOTT,ANALYST,7566.0,1982-12-09 00:00:00,3000,NaN,20
7,7839,KING,PRESIDENT,NaN,1981-11-17 00:00:00,5000,NaN,10
8,7844,TURNER,SALESMAN,7698.0,1981-09-08 00:00:00,1500,0.0,30
9,7876,ADAMS,CLERK,7788.0,1983-01-12 00:00:00,1100,NaN,20
10,7902,FORD,ANALYST,7566.0,1981-12-03 00:00:00,3000,NaN,20
11,7934,MILLER,CLERK,7782.0,1982-01-23 00:00:00,1300,NaN,10

In [ ]:
cur = con.cursor()

In [ ]:
sql = '''
drop table if exists greater_1000_SAL;
create table greater_1000_SAL as
select * from EMP e
where e.SAL > 1000
'''

In [ ]:
cur.executescript(sql)

In [ ]:
sql = '''select * from greater_1000_SAL t'''

In [ ]:
select (sql)

,EMPNO,ENAME,JOB,MGR,HIREDATE,SAL,COMM,DEPTNO
0,7499,ALLEN,SALESMAN,7698.0,1981-02-20 00:00:00,1600,300.0,30
1,7521,WARD,SALESMAN,7698.0,1981-02-22 00:00:00,1250,500.0,30
2,7566,JONES,MANAGER,7839.0,1981-04-02 00:00:00,2975,NaN,20
3,7654,MARTIN,SALESMAN,7698.0,1981-09-28 00:00:00,1250,1400.0,30
4,7698,BLAKE,MANAGER,7839.0,1981-05-01 00:00:00,2850,NaN,30
5,7782,CLARK,MANAGER,7839.0,1981-06-09 00:00:00,2450,NaN,10
6,7788,SCOTT,ANALYST,7566.0,1982-12-09 00:00:00,3000,NaN,20
7,7839,KING,PRESIDENT,NaN,1981-11-17 00:00:00,5000,NaN,10
8,7844,TURNER,SALESMAN,7698.0,1981-09-08 00:00:00,1500,0.0,30
9,7876,ADAMS,CLERK,7788.0,1983-01-12 00:00:00,1100,NaN,20
10,7902,FORD,ANALYST,7566.0,1981-12-03 00:00:00,3000,NaN,20
11,7934,MILLER,CLERK,7782.0,1982-01-23 00:00:00,1300,NaN,10

## Union all and Union

In [ ]:
jan = pd.DataFrame({'month':['jan','jan'],'revenue':[1,2]})
feb = pd.DataFrame({'month':['feb','feb'],'revenue':[1,2]})

In [ ]:
jan.to_sql('jan',con,index=False,if_exists='replace')
feb.to_sql('feb',con,index=False,if_exists='replace')

2

In [ ]:
sql = '''select * from jan t
union all
select * from feb t'''

In [ ]:
select(sql)

  month  revenue
0   jan        1
1   jan        2
2   feb        1
3   feb        2

In [ ]:
sql = '''select t.revenue from jan t
union
select t.revenue from feb t'''

In [ ]:
select(sql)

   revenue
0        1
1        2

In [ ]:
sql = '''select t.revenue,
'jan' as month
 from jan t
union all
select t.revenue,
'mar' as month
 from feb t'''

In [ ]:
select(sql)

   revenue month
0        1   jan
1        2   jan
2        1   mar
3        2   mar

## Специальные функции

In [ ]:
sql = '''select e.ENAME, substr(e.ENAME,1,1) from EMP e limit 5'''

In [ ]:
select(sql)

    ENAME substr(e.ENAME,1,1)
0   SMITH                   S
1   ALLEN                   A
2    WARD                   W
3   JONES                   J
4  MARTIN                   M

## Group by

In [ ]:
sql = '''select e.deptno, count(*) as cnt
from EMP e
group by e.deptno'''

In [ ]:
select(sql)

   DEPTNO  cnt
0      10    3
1      20    5
2      30    6

In [ ]:
sql = '''select 'hello' as msg,
1 as num,
deptno,
(select count(*) from emp e) as total,
count(*) as cnt
from emp e
group by deptno '''

In [ ]:
select(sql)

     msg  num  DEPTNO  total  cnt
0  hello    1      10     14    3
1  hello    1      20     14    5
2  hello    1      30     14    6

In [ ]:
sql = '''select e.deptno, e.job, count(*) as cnt
from emp e
group by e.deptno, e.job'''

In [ ]:
select(sql)

   DEPTNO        JOB  cnt
0      10      CLERK    1
1      10    MANAGER    1
2      10  PRESIDENT    1
3      20    ANALYST    2
4      20      CLERK    2
5      20    MANAGER    1
6      30      CLERK    1
7      30    MANAGER    1
8      30   SALESMAN    4

## Оконные функции

Простой пример

In [ ]:
sql = '''select e.ename,
e.deptno,
count(*) over () as cnt
from EMP e
order by 2'''

In [ ]:
select(sql)

     ENAME  DEPTNO  cnt
0    CLARK      10   14
1     KING      10   14
2   MILLER      10   14
3    SMITH      20   14
4    JONES      20   14
5    SCOTT      20   14
6    ADAMS      20   14
7     FORD      20   14
8    ALLEN      30   14
9     WARD      30   14
10  MARTIN      30   14
11   BLAKE      30   14
12  TURNER      30   14
13   JAMES      30   14

Порядок обработки

In [ ]:
sql = '''select e.ename,
e.deptno,
count(*) over () as cnt
from EMP e
where deptno = 10
order by 2'''

In [ ]:
select(sql)

    ENAME  DEPTNO  cnt
0   CLARK      10    3
1    KING      10    3
2  MILLER      10    3

Сегменты или группа строк

In [ ]:
sql = '''select e.ename,
e.deptno,
count(*) over(partition by e.deptno) as cnt
from EMP e
order by 2 '''

In [ ]:
select(sql)

     ENAME  DEPTNO  cnt
0    CLARK      10    3
1     KING      10    3
2   MILLER      10    3
3    SMITH      20    5
4    JONES      20    5
5    SCOTT      20    5
6    ADAMS      20    5
7     FORD      20    5
8    ALLEN      30    6
9     WARD      30    6
10  MARTIN      30    6
11   BLAKE      30    6
12  TURNER      30    6
13   JAMES      30    6

Предшествующий запрос можно рассматривать как более эффективную версию следующего запроса

In [ ]:
sql = '''select e.ename,
e.deptno,
(select count(*) from emp d
where e.deptno=d.deptno) as cnt
from emp e
order by 2'''

In [ ]:
select(sql)

     ENAME  DEPTNO  cnt
0    CLARK      10    3
1     KING      10    3
2   MILLER      10    3
3    SMITH      20    5
4    JONES      20    5
5    SCOTT      20    5
6    ADAMS      20    5
7     FORD      20    5
8    ALLEN      30    6
9     WARD      30    6
10  MARTIN      30    6
11   BLAKE      30    6
12  TURNER      30    6
13   JAMES      30    6

Еще одно полезное свойство оператора PARTITION BY состоит в том что он выполняет вычисления независимо от других оконных функций осуществляя сегментирование по другим столбцам в том же выражении SELECT

In [ ]:
sql = '''select e.ename,
e.deptno,
count(*) over (partition by e.deptno) as dept_cnt,
job,
count(*) over (partition by e.job) as job_cnt
from emp e
order by 2 '''

In [ ]:
select(sql)

     ENAME  DEPTNO  dept_cnt        JOB  job_cnt
0   MILLER      10         3      CLERK        4
1    CLARK      10         3    MANAGER        3
2     KING      10         3  PRESIDENT        1
3    SCOTT      20         5    ANALYST        2
4     FORD      20         5    ANALYST        2
5    SMITH      20         5      CLERK        4
6    ADAMS      20         5      CLERK        4
7    JONES      20         5    MANAGER        3
8    JAMES      30         6      CLERK        4
9    BLAKE      30         6    MANAGER        3
10   ALLEN      30         6   SALESMAN        4
11    WARD      30         6   SALESMAN        4
12  MARTIN      30         6   SALESMAN        4
13  TURNER      30         6   SALESMAN        4

Воздействие значений NULL

In [ ]:
sql = '''select coalesce(e.comm,-1) as comm,
count(*) over(partition by e.comm) as cnt
from emp e
order by 2
'''

In [ ]:
select(sql)

      comm  cnt
0      0.0    1
1    300.0    1
2    500.0    1
3   1400.0    1
4     -1.0   10
5     -1.0   10
6     -1.0   10
7     -1.0   10
8     -1.0   10
9     -1.0   10
10    -1.0   10
11    -1.0   10
12    -1.0   10
13    -1.0   10

In [ ]:
df_emp

    EMPNO   ENAME        JOB     MGR   HIREDATE   SAL    COMM  DEPTNO
0    7369   SMITH      CLERK  7902.0 1980-12-17   800     NaN      20
1    7499   ALLEN   SALESMAN  7698.0 1981-02-20  1600   300.0      30
2    7521    WARD   SALESMAN  7698.0 1981-02-22  1250   500.0      30
3    7566   JONES    MANAGER  7839.0 1981-04-02  2975     NaN      20
4    7654  MARTIN   SALESMAN  7698.0 1981-09-28  1250  1400.0      30
5    7698   BLAKE    MANAGER  7839.0 1981-05-01  2850     NaN      30
6    7782   CLARK    MANAGER  7839.0 1981-06-09  2450     NaN      10
7    7788   SCOTT    ANALYST  7566.0 1982-12-09  3000     NaN      20
8    7839    KING  PRESIDENT     NaN 1981-11-17  5000     NaN      10
9    7844  TURNER   SALESMAN  7698.0 1981-09-08  1500     0.0      30
10   7876   ADAMS      CLERK  7788.0 1983-01-12  1100     NaN      20
11   7900   JAMES      CLERK  7698.0 1981-12-03   950     NaN      30
12   7902    FORD    ANALYST  7566.0 1981-12-03  3000     NaN      20
13   7934  MILLER      CLERK  7782.0 1982-01-23  1300     NaN      10

Если в функцию COUNT вместо * передать COMM то результаты будут значительно иными. При использовании COUNT(*) считатются не значения столбцов а строки т.е. NULL учитывается

In [ ]:
sql = '''select coalesce(e.comm, -1) as comm,
count(e.comm) over(partition by e.comm) as cnt
from emp e
order by 2 desc'''

In [ ]:
select(sql)

      comm  cnt
0      0.0    1
1    300.0    1
2    500.0    1
3   1400.0    1
4     -1.0    0
5     -1.0    0
6     -1.0    0
7     -1.0    0
8     -1.0    0
9     -1.0    0
10    -1.0    0
11    -1.0    0
12    -1.0    0
13    -1.0    0

Когда порядок имеет значение

In [ ]:
sql = '''select
e.deptno,
e.ename,
e.hiredate,
e.sal,
sum(sal) over(partition by e.deptno) as total1,
sum(sal) over() as total2,
sum(sal) over(order by hiredate) as running_total
from emp e
where deptno =10'''

In [ ]:
select(sql)

   DEPTNO   ENAME             HIREDATE   SAL  total1  total2  running_total
0      10   CLARK  1981-06-09 00:00:00  2450    8750    8750           2450
1      10    KING  1981-11-17 00:00:00  5000    8750    8750           7450
2      10  MILLER  1982-01-23 00:00:00  1300    8750    8750           8750

Следующий запрос такой же как и предыдущий но в нем используется оператор RANGE BETWEEN чтобы явно задать поведение по умолчанию в результате применения ORDER BY HIREDATE

In [ ]:
sql = '''select
e.deptno,
e.ename,
e.hiredate,
e.sal,
sum(sal) over(partition by e.deptno) as total1,
sum(sal) over() as total2,
sum(sal) over(order by hiredate
                  range between unbounded preceding
                  and current row) as running_total
from emp e
where deptno =10'''

In [ ]:
select(sql)

   DEPTNO   ENAME             HIREDATE   SAL  total1  total2  running_total
0      10   CLARK  1981-06-09 00:00:00  2450    8750    8750           2450
1      10    KING  1981-11-17 00:00:00  5000    8750    8750           7450
2      10  MILLER  1982-01-23 00:00:00  1300    8750    8750           8750

Оператор кадрирования (RANGE BETWEEN)

In [ ]:
sql = ''' select
e.deptno,
e.ename,
e.sal,
sum(sal) over(order by e.hiredate
              range between unbounded preceding
              and current row) as run_total1,
sum(sal) over(order by e.hiredate
              rows between 1 preceding
              and current row) as run_total2,
sum(sal) over(order by e.hiredate
              range between current row
              and unbounded following) as run_total3,
sum(sal) over(order by e.hiredate
              rows between current row
              and 1 following) as run_total4
from emp e
where deptno = 10'''

In [ ]:
select(sql)

   DEPTNO   ENAME   SAL  run_total1  run_total2  run_total3  run_total4
0      10   CLARK  2450        2450        2450        8750        7450
1      10    KING  5000        7450        7450        6300        6300
2      10  MILLER  1300        8750        6300        1300        1300

In [ ]:
sql = '''select
ename,
sal,
min(sal) over(order by sal) min1,
max(sal) over(order by sal) max1,
min(sal) over(order by sal
              range between unbounded preceding
              and  unbounded following) min2,
max(sal) over(order by sal
              range between unbounded preceding
              and unbounded following) max2,
min(sal) over(order by sal
              range between current row
              and current row) min3,
max(sal) over(order by sal
              range between current row
              and current row) max3,
max(sal) over(order by sal
              rows between 3 preceding
              and 3 following) max4
from emp
'''

In [ ]:
select(sql)

     ENAME   SAL  min1  max1  min2  max2  min3  max3  max4
0    SMITH   800   800   800   800  5000   800   800  1250
1    JAMES   950   800   950   800  5000   950   950  1250
2    ADAMS  1100   800  1100   800  5000  1100  1100  1300
3     WARD  1250   800  1250   800  5000  1250  1250  1500
4   MARTIN  1250   800  1250   800  5000  1250  1250  1600
5   MILLER  1300   800  1300   800  5000  1300  1300  2450
6   TURNER  1500   800  1500   800  5000  1500  1500  2850
7    ALLEN  1600   800  1600   800  5000  1600  1600  2975
8    CLARK  2450   800  2450   800  5000  2450  2450  3000
9    BLAKE  2850   800  2850   800  5000  2850  2850  3000
10   JONES  2975   800  2975   800  5000  2975  2975  5000
11   SCOTT  3000   800  3000   800  5000  3000  3000  5000
12    FORD  3000   800  3000   800  5000  3000  3000  5000
13    KING  5000   800  5000   800  5000  5000  5000  5000

Удобочитаемость + производительность = мощность

- количество служащих в каждом отделе;
- количество разных должностей в каждом отделе (например, количество клерков в отделе 10);
- общее количество служащих в таблице EMP

In [ ]:
sql = '''select
e.deptno,
e.job,
count(*) over(partition by e.deptno) as emp_cnt,
count(job) over(partition by e.deptno, e.job) as job_cnt,
count(*) over() as total
from emp e
'''

In [ ]:
select(sql)

    DEPTNO        JOB  emp_cnt  job_cnt  total
0       10      CLERK        3        1     14
1       10    MANAGER        3        1     14
2       10  PRESIDENT        3        1     14
3       20    ANALYST        5        2     14
4       20    ANALYST        5        2     14
5       20      CLERK        5        2     14
6       20      CLERK        5        2     14
7       20    MANAGER        5        1     14
8       30      CLERK        6        1     14
9       30    MANAGER        6        1     14
10      30   SALESMAN        6        4     14
11      30   SALESMAN        6        4     14
12      30   SALESMAN        6        4     14
13      30   SALESMAN        6        4     14

чтобы получить такую же информацию без использования оконных функций потребовалось бы выполнить несколько больший обьем работ

In [ ]:
sql = '''select a.deptno, a.job,
(select count(*) from emp b
where b.deptno = a.deptno) as emp_cnt,
(select count(*) from emp b
where b.deptno = a.deptno and b.job = a.job) as job_cnt,
(select count(*) from emp) as total
from emp a
order by 1,2
 '''

In [ ]:
select(sql)

    DEPTNO        JOB  emp_cnt  job_cnt  total
0       10      CLERK        3        1     14
1       10    MANAGER        3        1     14
2       10  PRESIDENT        3        1     14
3       20    ANALYST        5        2     14
4       20    ANALYST        5        2     14
5       20      CLERK        5        2     14
6       20      CLERK        5        2     14
7       20    MANAGER        5        1     14
8       30      CLERK        6        1     14
9       30    MANAGER        6        1     14
10      30   SALESMAN        6        4     14
11      30   SALESMAN        6        4     14
12      30   SALESMAN        6        4     14
13      30   SALESMAN        6        4     14

Запросы "в стиле отчетов"

In [ ]:
sql = '''select deptno,
                job,
                count (*) over (partition by deptno) as emp_cnt,
                count (job) over (partition by deptno, job) as job_cnt,
                count (*) over () as total
         from emp'''

In [ ]:
select(sql)

    DEPTNO        JOB  emp_cnt  job_cnt  total
0       10      CLERK        3        1     14
1       10    MANAGER        3        1     14
2       10  PRESIDENT        3        1     14
3       20    ANALYST        5        2     14
4       20    ANALYST        5        2     14
5       20      CLERK        5        2     14
6       20      CLERK        5        2     14
7       20    MANAGER        5        1     14
8       30      CLERK        6        1     14
9       30    MANAGER        6        1     14
10      30   SALESMAN        6        4     14
11      30   SALESMAN        6        4     14
12      30   SALESMAN        6        4     14
13      30   SALESMAN        6        4     14

In [ ]:
sql = '''select deptno,
                emp_cnt as dept_total,
                total,
                max(case when job = 'CLERK'
                          then job_cnt else 0 end) as clerks,
                max(case when job = 'MANAGER'
                          then job_cnt else 0 end) as mgrs,
                max(case when job = 'PRESIDENT'
                          then job_cnt else 0 end) as prez,
                max(case when job = 'ANALYST'
                          then job_cnt else 0 end) as anals,
                max(case when job = 'SALESMAN'
                          then job_cnt else 0 end) as smen
          from (
          select deptno,
                job,
                count (*) over (partition by deptno) as emp_cnt,
                count (job) over (partition by deptno, job) as job_cnt,
                count (*) over () as total
         from emp
          ) x
          group by deptno, emp_cnt, total
      '''

In [ ]:
select(sql)

   deptno  dept_total  total  clerks  mgrs  prez  anals  smen
0      10           3     14       1     1     1      0     0
1      20           5     14       2     1     0      2     0
2      30           6     14       1     1     0      0     4

In [ ]:
sql = '''select ename as name,
                sal,
                max(sal) over(partition by deptno) as hiDpt,
                min(sal) over(partition by deptno) as loDpt,
                max(sal) over(partition by job) as hiJob,
                min(sal) over(partition by job) as loJob,
                max(sal) over() as hi,
                min(sal) over() as lo,
                sum(sal) over(partition by deptno
                                  order by sal, empno) as dptRT,
                sum(sal) over(partition by deptno) as dptSum,
                sum(sal) over() as ttl
            from emp
          order by deptno, dptRT
         '''

In [ ]:
select(sql)

      name   SAL  hiDpt  loDpt  hiJob  loJob    hi   lo  dptRT  dptSum    ttl
0   MILLER  1300   5000   1300   1300    800  5000  800   1300    8750  29025
1    CLARK  2450   5000   1300   2975   2450  5000  800   3750    8750  29025
2     KING  5000   5000   1300   5000   5000  5000  800   8750    8750  29025
3    SMITH   800   3000    800   1300    800  5000  800    800   10875  29025
4    ADAMS  1100   3000    800   1300    800  5000  800   1900   10875  29025
5    JONES  2975   3000    800   2975   2450  5000  800   4875   10875  29025
6    SCOTT  3000   3000    800   3000   3000  5000  800   7875   10875  29025
7     FORD  3000   3000    800   3000   3000  5000  800  10875   10875  29025
8    JAMES   950   2850    950   1300    800  5000  800    950    9400  29025
9     WARD  1250   2850    950   1600   1250  5000  800   2200    9400  29025
10  MARTIN  1250   2850    950   1600   1250  5000  800   3450    9400  29025
11  TURNER  1500   2850    950   1600   1250  5000  800   4950    9400  29025
12   ALLEN  1600   2850    950   1600   1250  5000  800   6550    9400  29025
13   BLAKE  2850   2850    950   2975   2450  5000  800   9400    9400  29025

In [ ]:
sql = '''select ename as name,
                sal,
                max(sal) over(partition by deptno) as hiDpt,
                min(sal) over(partition by deptno) as loDpt,
                max(sal) over(partition by job) as hiJob,
                min(sal) over(partition by job) as loJob,
                max(sal) over() as hi,
                min(sal) over() as lo,
                sum(sal) over(partition by deptno
                                  order by sal, empno) as dptRT,
                sum(sal) over(partition by deptno) as dptSum,
                sum(sal) over() as ttl
              from emp
          order by deptno, dptRT
      '''

In [ ]:
select(sql)

      name   SAL  hiDpt  loDpt  hiJob  loJob    hi   lo  dptRT  dptSum    ttl
0   MILLER  1300   5000   1300   1300    800  5000  800   1300    8750  29025
1    CLARK  2450   5000   1300   2975   2450  5000  800   3750    8750  29025
2     KING  5000   5000   1300   5000   5000  5000  800   8750    8750  29025
3    SMITH   800   3000    800   1300    800  5000  800    800   10875  29025
4    ADAMS  1100   3000    800   1300    800  5000  800   1900   10875  29025
5    JONES  2975   3000    800   2975   2450  5000  800   4875   10875  29025
6    SCOTT  3000   3000    800   3000   3000  5000  800   7875   10875  29025
7     FORD  3000   3000    800   3000   3000  5000  800  10875   10875  29025
8    JAMES   950   2850    950   1300    800  5000  800    950    9400  29025
9     WARD  1250   2850    950   1600   1250  5000  800   2200    9400  29025
10  MARTIN  1250   2850    950   1600   1250  5000  800   3450    9400  29025
11  TURNER  1500   2850    950   1600   1250  5000  800   4950    9400  29025
12   ALLEN  1600   2850    950   1600   1250  5000  800   6550    9400  29025
13   BLAKE  2850   2850    950   2975   2450  5000  800   9400    9400  29025

# Подзапросы и обобщенные табличные выражения

## Подзапросы

In [ ]:
sql = '''select job, count(empno) as HeadCount
from emp
group by job'''

In [ ]:
select(sql)

         JOB  HeadCount
0    ANALYST          2
1      CLERK          4
2    MANAGER          3
3  PRESIDENT          1
4   SALESMAN          4

In [ ]:
sql = '''select max (HeadCount) as HighestJobHeadCount from
(select job, count(empno) as HeadCount
from emp
group by job) head_count_tab '''

In [ ]:
select(sql)

   HighestJobHeadCount
0                    4

## Обобщенные табличные выражения

In [ ]:
sql = '''with head_count_tab (job, HeadCount) as
          (select job, count(empno)
              from emp
            group by job)
         select max(HeadCount) as HighestJobHeadCount
              from head_count_tab'''

In [ ]:
select(sql)

   HighestJobHeadCount
0                    4

## Рекурсивный подзапрос

Считаю до пяти

In [ ]:
sql = '''with recursive counter(n) as(
      select 1
      union all
      select n+1
      from counter
      where n<5
    )
    select n from counter '''

In [ ]:
select(sql)

   n
0  1
1  2
2  3
3  4
4  5

Добавил индекс (в даном случае индекс - счетчик)

In [ ]:
sql = '''with recursive counter(n, index1) as(
      select 1,0
      union all
      select n+1, index1+1
      from counter
      where index1<5
    )
    select n, index1 from counter '''

In [ ]:
select(sql)

   n  index1
0  1       0
1  2       1
2  3       2
3  4       3
4  5       4
5  6       5

Вычисление первых 20 значений последовательности Фибоначчи

In [ ]:
sql = '''with recursive workingTable(fibNum, NextNumber, index1)
as
(select 0,1,1
union all
select fibNum+nextNumber, fibNUm, index1+1
from workingTable
where index1<20)
select fibNum from workingTable as fib '''

In [ ]:
select(sql)

    fibNum
0        0
1        1
2        1
3        2
4        3
5        5
6        8
7       13
8       21
9       34
10      55
11      89
12     144
13     233
14     377
15     610
16     987
17    1597
18    2584
19    4181

# Индексы

Индекс в SQL — это структура данных для ускорения поиска (как алфавитный указатель в книге). Создаётся через CREATE INDEX, в SELECT не виден, на результат не влияет — только на скорость.

## Простой индекс на один столбец

In [ ]:
sql = '''DROP INDEX IF EXISTS idx_emp_deptno'''

In [ ]:
execute(sql)

In [ ]:
sql = '''CREATE INDEX idx_emp_deptno ON emp(DEPTNO)'''

In [ ]:
execute(sql)

## Проверка что индекс создался

In [ ]:
select("SELECT name, sql FROM sqlite_master WHERE type='index' AND tbl_name='EMP'")

             name                                         sql
0  idx_emp_deptno  CREATE INDEX idx_emp_deptno ON emp(DEPTNO)

In [ ]:
df_emp.dtypes

EMPNO                int64
ENAME               object
JOB                 object
MGR                float64
HIREDATE    datetime64[ns]
SAL                  int64
COMM               float64
DEPTNO               int64
dtype: object

In [ ]:
select("SELECT type, name, tbl_name FROM sqlite_master")

    type              name          tbl_name
0  table              DEPT              DEPT
1  table               EMP               EMP
2  table  greater_1000_SAL  greater_1000_SAL
3  table               jan               jan
4  table               feb               feb
5  index    idx_emp_deptno               EMP

# Проверка нагрузки запроса

In [ ]:
sql = '''DROP INDEX IF EXISTS idx_emp_deptno'''

In [ ]:
execute(sql)

In [ ]:
sql = '''EXPLAIN QUERY PLAN SELECT * FROM emp WHERE DEPTNO = 30'''

Сканирует таблицу целиком

In [ ]:
select(sql)

   id  parent  notused    detail
0   2       0        0  SCAN emp

In [ ]:
sql = '''CREATE INDEX idx_emp_deptno ON emp(DEPTNO)'''

In [ ]:
execute(sql)

In [ ]:
sql = '''EXPLAIN QUERY PLAN SELECT * FROM emp WHERE DEPTNO = 30'''

Искать по индексу

In [ ]:
select(sql)

   id  parent  notused                                            detail
0   3       0        0  SEARCH emp USING INDEX idx_emp_deptno (DEPTNO=?)

## Проверка какие таблицы есть

In [ ]:
sql = '''SELECT name, sql FROM sqlite_master WHERE type = 'table' '''

In [ ]:
select(sql)

               name                                                sql
0              DEPT  CREATE TABLE "DEPT" (\n"DEPTNO" INTEGER,\n  "D...
1               EMP  CREATE TABLE "EMP" (\n"EMPNO" INTEGER,\n  "ENA...
2  greater_1000_SAL  CREATE TABLE greater_1000_SAL(\n  EMPNO INT,\n...
3               jan  CREATE TABLE "jan" (\n"month" TEXT,\n  "revenu...
4               feb  CREATE TABLE "feb" (\n"month" TEXT,\n  "revenu...

In [ ]:
sql = ''' SELECT type, name, tbl_name FROM sqlite_master ORDER BY type, name '''

In [ ]:
select(sql)

    type              name          tbl_name
0  index    idx_emp_deptno               EMP
1  table              DEPT              DEPT
2  table               EMP               EMP
3  table               feb               feb
4  table  greater_1000_SAL  greater_1000_SAL
5  table               jan               jan

In [ ]:
sql = '''PRAGMA table_info(emp)'''

In [ ]:
select(sql)

   cid      name       type  notnull dflt_value  pk
0    0     EMPNO    INTEGER        0       None   0
1    1     ENAME       TEXT        0       None   0
2    2       JOB       TEXT        0       None   0
3    3       MGR       REAL        0       None   0
4    4  HIREDATE  TIMESTAMP        0       None   0
5    5       SAL    INTEGER        0       None   0
6    6      COMM       REAL        0       None   0
7    7    DEPTNO    INTEGER        0       None   0